[project]
name = "moonboard-analysis"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "matplotlib",
    "torch",
    "pandas",
    "scikit-learn",
    "seaborn",
    "adjusttext",
]

[project.optional-dependencies]
dev = [
    "jupyter",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []