remote_theme: pages-themes/cayman@v0.2.0
title: Moonboard Analysis & Machine Learning (ML) Benchmark
description: A machine learning benchmark for Moonboard climbing route grade prediction and route compression via autoencoders. Grade classification (LSTM, CNN, RF, MLP) and autoencoder compression on Moonboard climbing data.
show_downloads: true
google_analytics:

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO metadata
author: William Dennis
lang: en

social:
  name: Moonboard Analysis
  links:
    - https://github.com/wd7512/Moonboard-Analysis

# Twitter card
twitter:
  card: summary_large_image

# Default SEO defaults
defaults:
  - scope:
      path: ""
    values:
      image: https://opengraph.githubassets.com/1/wd7512/Moonboard-Analysis
